local_as: 65501
router_id: 1.1.1.1
neighbors:
  - peer_ip: 10.200.200.2
    peer_as: 65502
    advertised_networks:
      - net: "{{ interfaces.GigabitEthernet0/1.ip.address.ipv4_address | ipaddr('network') }}"
        mask: "{{ interfaces.GigabitEthernet0/1.ip.address.ipv4_address | ipaddr('hostmask') }}"
      - net: "{{interfaces.GigabitEthernet0/2.ip.address.ipv4_address  | ipaddr('network') }}"
        mask: "{{ interfaces.GigabitEthernet0/2.ip.address.ipv4_address | ipaddr('hostmask') }}"
      - net: "{{ interfaces.GigabitEthernet0/3.ip.address.ipv4_address  | ipaddr('network') }}"
        mask: "{{ interfaces.GigabitEthernet0/3.ip.address.ipv4_address | ipaddr('hostmask') }}"
      - net: "10.1.2.0"
        mask: "255.255.255.0"
      - net: "192.168.2.0"
        mask: "255.255.255.0"
